// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqn2_0xYixJTt-GIzNAnAuafa_48hZjyw',
    appId: '1:1062183347607:web:ff57376b7ad92c7a9350d2',
    messagingSenderId: '1062183347607',
    projectId: 'lobotony-96977',
    authDomain: 'lobotony-96977.firebaseapp.com',
    storageBucket: 'lobotony-96977.appspot.com',
    measurementId: 'G-C22109GP8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2yD0X7bgT-Fj4gRVtNflKYY-cGt_4Y4Y',
    appId: '1:1062183347607:android:9404a42e340af5089350d2',
    messagingSenderId: '1062183347607',
    projectId: 'lobotony-96977',
    storageBucket: 'lobotony-96977.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChHZFQcpqjJaGtugK9QO3ZkIri_Fhzwnw',
    appId: '1:1062183347607:ios:e9d10d0066d941289350d2',
    messagingSenderId: '1062183347607',
    projectId: 'lobotony-96977',
    storageBucket: 'lobotony-96977.appspot.com',
    iosBundleId: 'com.example.bakaplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChHZFQcpqjJaGtugK9QO3ZkIri_Fhzwnw',
    appId: '1:1062183347607:ios:e9d10d0066d941289350d2',
    messagingSenderId: '1062183347607',
    projectId: 'lobotony-96977',
    storageBucket: 'lobotony-96977.appspot.com',
    iosBundleId: 'com.example.bakaplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqn2_0xYixJTt-GIzNAnAuafa_48hZjyw',
    appId: '1:1062183347607:web:d6f0448ff03335019350d2',
    messagingSenderId: '1062183347607',
    projectId: 'lobotony-96977',
    authDomain: 'lobotony-96977.firebaseapp.com',
    storageBucket: 'lobotony-96977.appspot.com',
    measurementId: 'G-1SP47CMECT',
  );
}
